[package]
name = "kctf-pow"
version = "1.0.0"
edition = "2018"
description = "A library and CLI to solve, check, and generate proof-of-work challenges using kCTF's scheme."
license = "BSD-3"
authors = ["Aplet123 <aplet@aplet.me>"]

[dependencies]
rug = "1.12.0"
rand = "0.8.4"
base64 = "0.13.0"

[lib]
name = "kctf_pow"
path = "src/lib.rs"

[[bin]]
name = "kctf-pow-cli"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
